import { useMemo, useState } from "react";
import { ArrowLeft, CheckCircle2, CircleHelp, RotateCcw, Trophy } from "lucide-react";
import { Link, useSearchParams } from "react-router-dom";
import { useApp } from "../../app/AppContext";
import { normalizeQuiz, createQuestion } from "../content/contentSchema";

const fallbackQuestions=[
 {id:"water-1",text:"Which is a natural source of water?",options:["River","Notebook","Chair","Bag"],answer:0,explanation:"Rivers are natural sources of fresh water."},
 {id:"water-2",text:"Why should we save water?",options:["Water is unlimited","Fresh water is limited","Water is not useful","Only plants need water"],answer:1,explanation:"Fresh water is limited, so careful use helps every community."},
 {id:"water-3",text:"Which action helps conserve water?",options:["Leave taps running","Repair leaking taps","Waste clean water","Keep water uncovered"],answer:1,explanation:"Repairing leaks prevents clean water from being wasted."},
 {id:"water-4",text:"Which water source can be found underground?",options:["Well","Cloud","Rainbow","Sun"],answer:0,explanation:"Wells can reach groundwater below the surface."},
 {id:"water-5",text:"What should we do before drinking unsafe-looking water?",options:["Drink it immediately","Ignore it","Treat or filter it safely","Add soil"],answer:2,explanation:"Water should be treated or filtered using a safe method before drinking."},
];
function buildQuestions(quiz){const normalized=normalizeQuiz(quiz);if(normalized.questionItems?.length)return normalized.questionItems.map(createQuestion);return fallbackQuestions.slice(0,Math.max(1,Math.min(Number(quiz?.questions)||5,fallbackQuestions.length)));}
function saveAttempt(id,score,total){try{const key="sih26042:quiz-attempts";const items=JSON.parse(localStorage.getItem(key)||"[]");items.push({id:`attempt-${Date.now()}`,quizId:id,score,total,completedAt:new Date().toISOString()});localStorage.setItem(key,JSON.stringify(items.slice(-50)));}catch{}}

export default function QuizPlayer2Page(){
 const{state,actions}=useApp();const[params,setParams]=useSearchParams();const selectedId=params.get("quiz");const quiz=state.quizzes.find(q=>q.id===selectedId)||state.quizzes[0];const[activeId,setActiveId]=useState(selectedId||quiz?.id);const activeQuiz=state.quizzes.find(q=>q.id===activeId)||quiz;const questions=useMemo(()=>buildQuestions(activeQuiz),[activeQuiz]);const[index,setIndex]=useState(0);const[answers,setAnswers]=useState({});const[finished,setFinished]=useState(false);const current=questions[index];const score=questions.reduce((sum,q,i)=>sum+(answers[i]===q.answer?1:0),0);const answered=Object.keys(answers).length;
 if(!activeQuiz)return <div className="page quiz2"><div className="quiz2-empty"><CircleHelp/><h1>No quiz available</h1><p>Create a quiz from the teacher content studio first.</p><Link className="btn btn-primary" to="/student">Back home</Link></div></div>;
 if(!selectedId&&!finished&&state.quizzes.length>1&&activeId===quiz.id&&index===0&&answered===0){return <div className="page quiz2"><div className="quiz2-top"><Link to="/student" className="back-link"><ArrowLeft size={16}/> Back</Link></div><div className="quiz2-hero"><div><span className="eyebrow">Practice</span><h1>Choose a quiz</h1><p className="muted">Pick a quiz to start. Your attempts stay on this device.</p></div></div><div className="quiz2-library-grid">{state.quizzes.map(q=><button className="card quiz2-library-card" key={q.id} onClick={()=>{setActiveId(q.id);setParams({quiz:q.id});setIndex(0);setAnswers({});}}><span className="tag">{q.level||"Practice"}</span><h2>{q.title}</h2><p>{q.questionItems?.length||q.questions||0} questions</p><span className="btn btn-secondary">Start quiz</span></button>)}</div></div>}
 function choose(option){if(!finished)setAnswers(old=>({...old,[index]:option}));}
 function next(){if(index<questions.length-1)setIndex(i=>i+1);else{actions.saveQuizScore(activeQuiz.id,score);saveAttempt(activeQuiz.id,score,questions.length);setFinished(true);}}
 function restart(){setIndex(0);setAnswers({});setFinished(false);}
 if(finished){const pct=Math.round(score/questions.length*100);return <div className="page quiz2"><div className="quiz2-result card"><div className="quiz2-result-icon"><Trophy/></div><span className="eyebrow">Quiz complete</span><h1>{score}/{questions.length}</h1><p className="muted">{pct===100?"Excellent work! You got every answer right.":pct>=60?"Good job. Review the explanations and try again when ready.":"Keep practising. Review each explanation and try again."}</p><div className="quiz2-result-bar"><span style={{width:`${pct}%`}}/></div><div className="quiz2-result-actions"><button className="btn btn-primary" onClick={restart}><RotateCcw size={17}/> Try again</button><Link className="btn btn-secondary" to="/student">Back to learning</Link></div></div></div>}
 const selected=answers[index];const explanation=selected!==undefined?current.explanation:null;
 return <div className="page quiz2"><div className="quiz2-top"><Link to="/student/quizzes" className="back-link"><ArrowLeft size={16}/> All quizzes</Link><span className="badge">{answered}/{questions.length} answered</span></div><div className="quiz2-hero"><div><span className="eyebrow">Practice check</span><h1>{activeQuiz.title}</h1><p className="muted">Question {index+1} of {questions.length} · Saved on this device.</p></div><div className="quiz2-progress"><span style={{width:`${((index+1)/questions.length)*100}%`}}/></div></div><div className="quiz2-layout"><section className="card quiz2-question"><div className="quiz2-question-number">Q{index+1}</div><h2>{current.text}</h2><div className="quiz2-options">{current.options.map((option,oi)=>{const chosen=selected===oi;return <button key={`${current.id}-${oi}`} className={`quiz2-option ${chosen?"selected":""}`} onClick={()=>choose(oi)}><span className="quiz2-letter">{String.fromCharCode(65+oi)}</span><span>{option}</span>{chosen&&<CheckCircle2 size={18}/>}</button>})}</div>{selected!==undefined&&<div className="quiz2-feedback"><CheckCircle2 size={18}/><div><strong>{selected===current.answer?"Correct answer":"Answer selected"}</strong><span>{explanation}</span></div></div>}<div className="quiz2-footer"><span>{selected===undefined?"Choose one answer":"Ready to continue"}</span><button className="btn btn-primary" disabled={selected===undefined} onClick={next}>{index===questions.length-1?"Finish quiz":"Next question"}</button></div></section><aside className="quiz2-side card"><span className="eyebrow">Question map</span><div className="quiz2-map">{questions.map((q,i)=><button key={q.id} className={`${i===index?"current":""} ${answers[i]!==undefined?"answered":""}`} onClick={()=>setIndex(i)}>{i+1}</button>)}</div><div className="quiz2-note"><CircleHelp size={17}/><span>No internet is required once quiz content is available locally.</span></div></aside></div></div>;
}
