import { useEffect, useMemo, useState } from "react";
import { BookOpen, BarChart3, Check, ChevronRight, CircleHelp, GraduationCap, Home, Languages, Layers3, Menu, Settings, Users, Wifi, WifiOff, X, Bot, HardDriveDownload } from "lucide-react";
import { Link, NavLink, Navigate, Route, Routes, useNavigate } from "react-router-dom";
import { AppContext, useApp } from "./AppContext";
import { queueOfflineChange } from "../features/offline/offlineSync";
import TeacherDashboardPage from "../features/teacher/TeacherDashboardPage";
import TeacherContentStudio2Page from "../features/teacher/TeacherContentStudio2Page";
import ClassroomManagement2Page from "../features/teacher/ClassroomManagement2Page";
import QuizPlayer2Page from "../features/student/QuizPlayer2Page";
import StudentLessonPlayer2Page from "../features/student/StudentLessonPlayer2Page";
import TeacherProgress2Page from "../features/teacher/TeacherProgress2Page";
import StudentProgress2Page from "../features/student/StudentProgress2Page";
import LanguageAssistantPanel from "../components/common/LanguageAssistantPanel";
import AITutorPage from "../features/student/tutor/AITutorPage";
import StudentJourneyPage from "../features/student/StudentJourneyPage";
import OfflineCenterPage from "../features/offline/OfflineCenterPage";
import ModelStatusPanel from "../features/ai/ModelStatusPanel";
import ProductionReadinessPanel from "../features/system/ProductionReadinessPanel";
const seedLessons=[{id:"water",subjectId:"evs",title:"Water Around Us",description:"Sources of water, safe water and daily conservation.",minutes:10,level:"Grade 3"},{id:"plants",subjectId:"evs",title:"Plants Near Me",description:"Identify common plants and how they help our community.",minutes:12,level:"Grade 3"},{id:"numbers",subjectId:"math",title:"Numbers & Place Value",description:"Read, compare and build numbers with place value.",minutes:12,level:"Grade 3"}];
const seedFlashcards=[{id:"fc1",front:"What is a source of water?",back:"A river, pond, well or another place from which we get water."},{id:"fc2",front:"Why should we save water?",back:"Fresh water is limited and every community needs it."},{id:"fc3",front:"What is place value?",back:"The value of a digit depends on its position in a number."}];
const initialState={role:null,user:null,language:"en",lessons:seedLessons,quizzes:[{id:"q1",title:"Water Check",questions:5,level:"Grade 3",items:[{id:"water-1",text:"Which is a natural source of water?",options:["River","Notebook","Chair","Bag"],answer:0,explanation:"Rivers are natural sources of fresh water."},{id:"water-2",text:"Why should we save water?",options:["Water is unlimited","Fresh water is limited","Water is not useful","Only plants need water"],answer:1,explanation:"Fresh water is limited, so careful use helps every community."},{id:"water-3",text:"Which action helps conserve water?",options:["Leave taps running","Repair leaking taps","Waste clean water","Keep water uncovered"],answer:1,explanation:"Repairing leaks prevents clean water from being wasted."},{id:"water-4",text:"Which water source can be found underground?",options:["Well","Cloud","Rainbow","Sun"],answer:0,explanation:"Wells can reach groundwater below the surface."},{id:"water-5",text:"What should we do before drinking unsafe-looking water?",options:["Drink it immediately","Ignore it","Treat or filter it safely","Add soil"],answer:2,explanation:"Water should be treated or filtered using a safe method before drinking."}]}],flashcards:seedFlashcards,progress:{completedLessons:[],quizScores:{}}};
function usePersistentState(){const[state,setState]=useState(()=>{try{return JSON.parse(localStorage.getItem("sih26042-state"))||initialState}catch{return initialState}});useEffect(()=>localStorage.setItem("sih26042-state",JSON.stringify(state)),[state]);return[state,setState]}
export default function App(){const[state,setState]=usePersistentState();const[online,setOnline]=useState(()=>navigator.onLine);useEffect(()=>{const on=()=>setOnline(true),off=()=>setOnline(false);addEventListener("online",on);addEventListener("offline",off);return()=>{removeEventListener("online",on);removeEventListener("offline",off)}},[]);const actions=useMemo(()=>({selectRole:role=>setState(s=>({...s,role})),setupUser:user=>setState(s=>({...s,user})),setLanguage:language=>{setState(s=>({...s,language}));queueOfflineChange("language-change",{language})},completeLesson:id=>{setState(s=>s.progress.completedLessons.includes(id)?s:{...s,progress:{...s.progress,completedLessons:[...s.progress.completedLessons,id]}});queueOfflineChange("lesson-completed",{lessonId:id})},saveQuizScore:(id,score)=>{setState(s=>({...s,progress:{...s.progress,quizScores:{...s.progress.quizScores,[id]:score}}));queueOfflineChange("quiz-score",{quizId:id,score})},reset:()=>setState(initialState),addLesson:lesson=>{setState(s=>({...s,lessons:[...s.lessons,lesson]}));queueOfflineChange("lesson-created",{lesson})},addQuiz:quiz=>{setState(s=>({...s,quizzes:[...s.quizzes,quiz]}));queueOfflineChange("quiz-created",{quiz})},addFlashcard:card=>{setState(s=>({...s,flashcards:[...s.flashcards,card]}));queueOfflineChange("flashcard-created",{card})}}),[setState]);return <AppContext.Provider value={{state,actions,online}}><Routes><Route path="/" element={<Welcome/>}/><Route path="/role" element={<Role/>}/><Route path="/setup" element={<Setup/>}/><Route path="/teacher/*" element={<Gate role="teacher"><Shell role="teacher"><TeacherRoutes/></Shell></Gate>}/><Route path="/student/*" element={<Gate role="student"><Shell role="student"><StudentRoutes/></Shell></Gate>}/><Route path="*" element={<Navigate to="/" replace/>}/></Routes></AppContext.Provider>}
function Welcome(){const nav=useNavigate();return <main className="welcome-page"><div className="welcome-visual"><div className="brand-mark"><BookOpen size={30}/></div><span>SIH 26042</span><span className="pill"><WifiOff size={14}/> Offline-first</span></div><section className="welcome-card"><div className="eyebrow">Learning that keeps going</div><h1>Digital learning for <span>real classrooms.</span></h1><p>Lessons, quizzes, revision, language support, AI guidance and classroom tools that remain useful when connectivity is limited.</p><div className="feature-list"><div><WifiOff/> Works offline</div><div><GraduationCap/> Teacher + student modes</div><div><Languages/> Local-language ready</div></div><button className="btn btn-primary btn-lg" onClick={()=>nav("/role")}>Get started <ChevronRight size={19}/></button></section><div className="welcome-footer"><span>Designed for rural and low-connectivity learning environments.</span><span>Data stays on this device.</span></div></main>}
function Role(){const{actions}=useApp();const nav=useNavigate();return <main className="center-page"><div className="auth-panel"><Link to="/" className="back-link">← Back</Link><div className="eyebrow">Choose your workspace</div><h1>Who is using SIH 26042?</h1><p className="muted">Choose the tools you need on this device.</p><div className="role-grid"><button className="role-card" onClick={()=>{actions.selectRole("student");nav("/setup")}}><div className="role-icon student"><GraduationCap/></div><strong>Student</strong><span>Learn, revise, take quizzes, ask the AI tutor and track progress.</span></button><button className="role-card" onClick={()=>{actions.selectRole("teacher");nav("/setup")}}><div className="role-icon teacher"><Users/></div><strong>Teacher</strong><span>Create content, manage classrooms and review progress.</span></button></div></div></main>}
function Setup(){const{state,actions}=useApp();const nav=useNavigate();const[name,setName]=useState("");const role=state.role||"student";return <main className="center-page"><form className="auth-panel form-panel" onSubmit={e=>{e.preventDefault();actions.setupUser({name:name.trim()||role});nav(`/${role}`)}}><Link to="/role" className="back-link">← Change role</Link><div className="eyebrow">Local profile</div><h1>Set up this device</h1><p className="muted">No account or server is required for the core classroom experience.</p><label>Your name<input value={name} onChange={e=>setName(e.target.value)} placeholder={role==="teacher"?"e.g. Anita Ma'am":"e.g. Ravi"}/></label><label>Default language<select value={state.language} onChange={e=>actions.setLanguage(e.target.value)}><option value="en">English</option><option value="hi">हिन्दी</option><option value="san">Santhali</option><option value="bn">বাংলা</option><option value="ta">தமிழ்</option><option value="te">తెలుగు</option><option value="mr">मराठी</option></select></label><button className="btn btn-primary btn-lg">Open {role} workspace <ChevronRight size={18}/></button></form></main>}
function Gate({role,children}){const{state}=useApp();return state.role===role&&state.user?children:<Navigate to="/" replace/>}
function Shell({role,children}){const{state,online}=useApp();const[open,setOpen]=useState(false);const nav=role==="teacher"?[["/teacher","Dashboard",Home],["/teacher/content","Studio",BookOpen],["/teacher/classroom","Classroom",Users],["/teacher/offline","Offline Center",HardDriveDownload],["/teacher/progress","Progress",BarChart3],["/teacher/languages","Languages",Languages],["/teacher/settings","Settings",Settings]]:[["/student","Home",Home],["/student/lessons","Learn",BookOpen],["/student/tutor","AI Tutor",Bot],["/student/revision","Revision",Layers3],["/student/quizzes","Quizzes",CircleHelp],["/student/offline","Offline Center",HardDriveDownload],["/student/progress","Progress",BarChart3],["/student/languages","Languages",Languages],["/student/settings","Settings",Settings]];return <div className={`app-shell ${role}`}><header className="topbar"><button className="icon-btn mobile-only" onClick={()=>setOpen(v=>!v)}>{open?<X/>:<Menu/>}</button><Link to={`/${role}`} className="app-logo"><div className="mini-logo"><BookOpen size={18}/></div><div><strong>SIH 26042</strong><span>{role} workspace</span></div></Link><div className="top-actions"><span className={`network ${online?"ok":"warn"}`}>{online?<Wifi size={15}/>:<WifiOff size={15}/>} {online?"Online":"Offline"}</span><span className="lang-chip">{state.language.toUpperCase()}</span><span className="avatar">{state.user.name.slice(0,1).toUpperCase()}</span></div></header><div className="shell-body"><aside className={`sidebar ${open?"open":""}`} onClick={()=>setOpen(false)}><div className="side-label">Workspace</div>{nav.map(([to,label,Icon])=><NavLink key={to} to={to} end={to===`/${role}`} className={({isActive})=>`nav-item ${isActive?"active":""}`}><Icon size={18}/><span>{label}</span></NavLink>)}<div className="side-spacer"/><div className="offline-card"><WifiOff size={18}/><div><strong>Offline ready</strong><span>Changes save on-device</span></div></div></aside><main className="main-content">{children}</main></div><nav className="mobile-nav">{nav.slice(0,5).map(([to,label,Icon])=><NavLink key={to} to={to} end={to===`/${role}`}><Icon size={18}/><span>{label}</span></NavLink>)}</nav></div>}
function TeacherRoutes(){return <Routes><Route index element={<TeacherDashboardPage/>}/><Route path="content" element={<TeacherContentStudio2Page/>}/><Route path="classroom" element={<ClassroomManagement2Page/>}/><Route path="offline" element={<OfflineCenterPage/>}/><Route path="progress" element={<TeacherProgress2Page/>}/><Route path="languages" element={<LanguageTools/>}/><Route path="settings" element={<><SettingsPage/><ModelStatusPanel/><ProductionReadinessPanel/></>}/><Route path="*" element={<Navigate to="/teacher" replace/>}/></Routes>}
function StudentRoutes(){return <Routes><Route index element={<StudentJourneyPage/>}/><Route path="lessons" element={<StudentLessons/>}/><Route path="lessons/:lessonId" element={<StudentLessonPlayer2Page/>}/><Route path="tutor" element={<AITutorPage/>}/><Route path="revision" element={<StudentRevision/>}/><Route path="quizzes" element={<QuizPlayer2Page/>}/><Route path="offline" element={<OfflineCenterPage/>}/><Route path="progress" element={<StudentProgress2Page/>}/><Route path="languages" element={<LanguageTools/>}/><Route path="settings" element={<><SettingsPage/><ModelStatusPanel/><ProductionReadinessPanel/></>}/><Route path="*" element={<Navigate to="/student" replace/>}/></Routes>}
function StudentLessons(){const{state}=useApp();return <div className="page"><Header eyebrow="Learn" title="Lessons" description="Short lessons designed for offline study."/><div className="lesson-grid">{state.lessons.map(l=>{const done=state.progress.completedLessons.includes(l.id);return <article className={`lesson-card ${done?"done":""}`} key={l.id}><div className="lesson-top"><span className="tag">{l.level}</span>{done&&<span className="done-badge"><Check size={14}/> Done</span>}</div><div className="lesson-icon"><BookOpen size={21}/></div><h3>{l.title}</h3><p>{l.description}</p><div className="lesson-bottom"><span>{l.minutes} min</span><Link className="btn btn-secondary" to={`/student/lessons/${l.id}`}>{done?"Review":"Start lesson"} <ChevronRight size={15}/></Link></div></article>})}</div></div>}
function StudentRevision(){const{state}=useApp();const[i,setI]=useState(0);const[flip,setFlip]=useState(false);if(!state.flashcards.length)return <div className="page"><Header eyebrow="Revision" title="Flashcards" description="Your revision deck is empty."/></div>;const c=state.flashcards[i%state.flashcards.length];return <div className="page"><Header eyebrow="Revision" title="Flashcards" description="Think first, then reveal the answer."/><div className="flash-wrap"><button className={`flashcard ${flip?"flip":""}`} onClick={()=>setFlip(v=>!v)}><div className="face front"><span>QUESTION</span><h2>{c.front}</h2><small>Tap to reveal</small></div><div className="face back"><span>ANSWER</span><h2>{c.back}</h2><small>Tap to return</small></div></button><div className="flash-controls"><button className="btn btn-secondary" onClick={()=>{setI((i+state.flashcards.length-1)%state.flashcards.length);setFlip(false)}}>Previous</button><span>{i+1} / {state.flashcards.length}</span><button className="btn btn-primary" onClick={()=>{setI((i+1)%state.flashcards.length);setFlip(false)}}>Next <ChevronRight size={17}/></button></div></div></div>}
function LanguageTools(){return <div className="page"><Header eyebrow="Language & audio" title="Language assistant" description="Translate content and preview audio. Offline translations are saved on this device."/><LanguageAssistantPanel/></div>}
function SettingsPage(){const{state,actions}=useApp();const nav=useNavigate();return <div className="page"><Header eyebrow="Settings" title="Device settings" description="Local profile, model connections and offline storage controls."/><section className="card"><div className="setting-row"><div><strong>Profile</strong><span>{state.user.name} · {state.role}</span></div></div><div className="setting-row"><div><strong>Storage</strong><span>Learning data is saved locally in your browser.</span></div></div><button className="btn btn-secondary" onClick={()=>{actions.reset();nav("/")}}>Reset device data</button></section></div>}
function Header({eyebrow,title,description}){return <div className="page-header"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p className="muted">{description}</p></div></div>}
