import { useMemo, useRef, useState } from "react";
import { Archive, Check, CloudOff, Download, FileText, Headphones, Languages, Layers3, RefreshCw, Upload, Wifi, WifiOff, PackageCheck, ListChecks } from "lucide-react";
import { useApp } from "../../app/AppContext";
import { loadOfflineState, markOfflineSync, toggleOfflineItem } from "./offlineStore";
import { cacheAppShell, cacheLearningItem, getOfflineContent, removeLearningItem } from "./offlineCache";
import { exportOfflinePackage, importOfflinePackage, getPendingChanges, markChangesReadyForSync } from "./offlineSync";
import { getOfflineAssetStatus, setOfflineAsset } from "./offlinePackage";
import { loadClassroom, saveClassroom } from "../teacher/classroomStore";

export default function OfflineCenterPage(){
 const {state,online}=useApp(); const [offline,setOffline]=useState(loadOfflineState); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(""); const [cached,setCached]=useState(0); const [queue,setQueue]=useState(getPendingChanges); const [assets,setAssets]=useState(getOfflineAssetStatus); const fileRef=useRef(null);
 const items=useMemo(()=>[
   ...state.lessons.map(x=>({id:`lesson:${x.id}`,type:"lesson",title:x.title,meta:`${x.level} · ${x.minutes} min`,icon:FileText,data:x})),
   ...state.quizzes.map(x=>({id:`quiz:${x.id}`,type:"quiz",title:x.title,meta:`${x.level} · ${x.questions || x.questionItems?.length || x.items?.length || 0} questions`,icon:Archive,data:x})),
   ...state.flashcards.map(x=>({id:`flashcard:${x.id}`,type:"flashcard",title:x.front,meta:"Revision card",icon:Layers3,data:x}))
 ],[state.lessons,state.quizzes,state.flashcards]);
 const enabled=items.filter(x=>offline.downloads[x.id]);
 const refresh=async()=>{setCached((await getOfflineContent()).length);setQueue(getPendingChanges());setAssets(getOfflineAssetStatus());};
 const toggle=async item=>{const ready=!!offline.downloads[item.id];setBusy(true);setMessage("");try{if(!ready)await cacheLearningItem(item.data);else await removeLearningItem(item.data.id);setOffline(toggleOfflineItem(item.id,!ready));setMessage(ready?`${item.title} removed from offline library.`:`${item.title} is ready for offline use.`);await refresh();}catch{setMessage("Could not update the offline library.");}finally{setBusy(false);}};
 const prepareAll=async()=>{setBusy(true);setMessage("");try{await cacheAppShell();for(const item of items)await cacheLearningItem(item.data);const next={...offline,downloads:Object.fromEntries(items.map(i=>[i.id,true]))};localStorage.setItem("sih26042:offline-center",JSON.stringify(next));setOffline(next);markOfflineSync();await refresh();setMessage("All lessons, quizzes and revision cards are prepared for offline use.");}catch{setMessage("Offline preparation could not be completed.");}finally{setBusy(false);}};
 const sync=async()=>{setBusy(true);setMessage("");try{await cacheAppShell();const next=markChangesReadyForSync();markOfflineSync();setOffline(loadOfflineState());setQueue(next.filter(x=>x.status==="pending"));setMessage(online?"Local changes are marked ready for the next sync or export.":"You are offline. Changes remain safely queued on this device.");}finally{setBusy(false);}};
 const markAsset=(kind,label)=>{setOfflineAsset(kind,{ready:true,label});setAssets(getOfflineAssetStatus());setMessage(`${label} reserved for offline use. Connect the real model/package to replace this placeholder.`);};
 const downloadPackage=()=>{const payload=exportOfflinePackage(state,loadClassroom(),offline);const blob=new Blob([JSON.stringify(payload,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`sih26042-offline-package-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url);setMessage("Offline package exported successfully.");};
 const chooseImport=()=>fileRef.current?.click();
 const importPackage=async(event)=>{const file=event.target.files?.[0];event.target.value="";if(!file)return;setBusy(true);try{const payload=JSON.parse(await file.text());importOfflinePackage(payload);saveClassroom(payload.classroom);setMessage("Offline package imported. Reloading…");setTimeout(()=>window.location.reload(),500);}catch{setMessage("Import failed. Choose a valid SIH 26042 package.");}finally{setBusy(false);}};
 return <div className="page offline-center"><input ref={fileRef} type="file" accept="application/json,.json" hidden onChange={importPackage}/>
  <div className="page-header"><div><div className="eyebrow">Device & connectivity</div><h1>Offline Center</h1><p className="muted">Prepare learning, language and model resources before connectivity drops.</p></div><div className={`offline-status ${online?"online":"offline"}`}>{online?<Wifi size={16}/>:<WifiOff size={16}/>} {online?"Connected":"Offline"}</div></div>
  <section className="offline-hero card"><div className="offline-hero-icon"><CloudOff/></div><div><span className="eyebrow">One-tap preparation</span><h2>Keep the classroom running without internet.</h2><p>The app shell, all current learning content and queued local changes can be prepared on this device.</p></div><div className="offline-hero-actions"><button className="btn btn-primary" onClick={prepareAll} disabled={busy}>{busy?<RefreshCw className="spin" size={16}/>:<PackageCheck size={16}/>} Prepare everything</button><button className="btn btn-secondary" onClick={sync} disabled={busy}><RefreshCw size={16}/> {online?"Prepare sync":"Save queue"}</button></div></section>
  {message&&<div className="offline-message" role="status"><Check size={16}/>{message}</div>}
  <div className="offline-stats"><div className="card offline-stat"><Download size={18}/><strong>{enabled.length}</strong><span>Learning items ready</span></div><div className="card offline-stat"><ListChecks size={18}/><strong>{queue.length}</strong><span>Changes waiting</span></div><div className="card offline-stat"><Languages size={18}/><strong>{assets.languagePacks?"Ready":"7"}</strong><span>Language support</span></div><div className="card offline-stat"><RefreshCw size={18}/><strong>{cached}</strong><span>Cached snapshots</span></div></div>
  <section className="card"><div className="card-head"><div><h2>Offline learning library</h2><p>Lessons, quizzes and revision cards can be stored on this device.</p></div><span className="offline-ready-pill"><Check size={14}/>{enabled.length}/{items.length} ready</span></div><div className="offline-list">{items.map(item=>{const Icon=item.icon;const ready=!!offline.downloads[item.id];return <div className={`offline-item ${ready?"ready":""}`} key={item.id}><div className="offline-item-icon"><Icon size={18}/></div><div className="offline-item-copy"><strong>{item.title}</strong><span>{item.meta}</span></div><button className={`offline-toggle ${ready?"active":""}`} disabled={busy} onClick={()=>toggle(item)}>{ready?<><Check size={15}/> Ready offline</>:<><Download size={15}/> Make available</>}</button></div>})}</div></section>
  <section className="card offline-assets"><div className="card-head"><div><h2>Offline capability packs</h2><p>Reserve local slots for the trained language, audio and AI assets.</p></div></div><div className="offline-asset-grid"><Asset icon={Languages} title="Language packs" ready={assets.languagePacks} onClick={()=>markAsset("languagePacks","Language pack")}/><Asset icon={Headphones} title="Audio resources" ready={assets.audio} onClick={()=>markAsset("audio","Audio resources")}/><Asset icon={PackageCheck} title="AI model assets" ready={assets.models} onClick={()=>markAsset("models","AI model assets")}/></div></section>
  <section className="card offline-transfer"><div><span className="eyebrow">Device transfer</span><h2>Move a classroom package without a server</h2><p>Export local classes, assignments, learning data and queued changes. Import it on another trusted device when required.</p></div><div className="offline-transfer-actions"><button className="btn btn-secondary" onClick={downloadPackage}><Download size={16}/> Export package</button><button className="btn btn-primary" onClick={chooseImport}><Upload size={16}/> Import package</button></div></section>
  <section className="offline-explainer"><div><strong>Offline engine</strong><p>Service-worker caching keeps the app shell available, Cache Storage keeps selected content snapshots, localStorage preserves progress and the sync queue records changes until a future server or manual package transfer can reconcile them.</p></div><div className="offline-flow"><span>Prepare</span><b>→</b><span>Learn offline</span><b>→</b><span>Queue</span><b>→</b><span>Sync later</span></div></section>
 </div>;
}
function Asset({icon:Icon,title,ready,onClick}){return <div className={`offline-asset ${ready?"ready":""}`}><div className="offline-asset-icon"><Icon size={19}/></div><div><strong>{title}</strong><span>{ready?"Marked ready on this device":"Not prepared yet"}</span></div><button className="btn btn-secondary" onClick={onClick}>{ready?<><Check size={15}/> Ready</>:"Prepare slot"}</button></div>}
