import { useEffect, useMemo, useState } from "react";
import { BookOpen, CheckCircle2, Plus, Users, UserPlus } from "lucide-react";
import { assignContent, addStudent, createClassroom, loadClassroom } from "./classroomStore";
import { useApp } from "../../app/AppContext";

export default function TeacherClassroomPage() {
  const { state } = useApp();
  const [data, setData] = useState(loadClassroom());
  const [className, setClassName] = useState("");
  const [studentName, setStudentName] = useState("");
  const [activeClass, setActiveClass] = useState("");
  const [contentId, setContentId] = useState("");
  const refresh = () => setData(loadClassroom());
  const selected = data.classes.find(c => c.id === activeClass) || data.classes[0];
  const classStudents = useMemo(() => data.students.filter(s => !selected || s.classId === selected.id), [data.students, selected]);
  const create = e => { e.preventDefault(); if (!className.trim()) return; const item = createClassroom({ name: className.trim(), grade: "Grade 3", language: state.language }); setClassName(""); setActiveClass(item.id); refresh(); };
  const add = e => { e.preventDefault(); if (!studentName.trim() || !selected) return; addStudent({ name: studentName.trim(), classId: selected.id }); setStudentName(""); refresh(); };
  const assign = () => { if (!selected || !contentId) return; assignContent({ classId: selected.id, contentId, contentType: contentId.startsWith("q") ? "quiz" : "lesson" }); setContentId(""); refresh(); };
  return <div className="page"><div className="page-header"><div><div className="eyebrow">Teacher workspace</div><h1>Classroom</h1><p className="muted">Create classes, add learners and assign offline content.</p></div></div><div className="classroom-layout"><section className="card"><div className="card-head"><div><h2>My classes</h2><p>Create a local classroom on this device.</p></div><Users size={20}/></div>{data.classes.length ? <div className="class-list">{data.classes.map(c => <button key={c.id} className={`class-row ${selected?.id===c.id?"active":""}`} onClick={()=>setActiveClass(c.id)}><span>{c.name}</span><small>{c.grade} · {c.language.toUpperCase()}</small></button>)}</div> : <p className="muted">No classes yet.</p>}<form className="inline-form" onSubmit={create}><input value={className} onChange={e=>setClassName(e.target.value)} placeholder="Class name, e.g. Grade 3 A"/><button className="btn btn-primary"><Plus size={17}/> Create</button></form></section><section className="card"><div className="card-head"><div><h2>{selected?.name || "Select a class"}</h2><p>{selected ? "Local roster and assignments" : "Create your first class to begin."}</p></div><span className="badge">{classStudents.length} students</span></div>{selected && <><form className="inline-form" onSubmit={add}><input value={studentName} onChange={e=>setStudentName(e.target.value)} placeholder="Student name"/><button className="btn btn-secondary"><UserPlus size={17}/> Add student</button></form><div className="roster">{classStudents.length ? classStudents.map(s=><div className="roster-row" key={s.id}><span className="avatar">{s.name[0].toUpperCase()}</span><strong>{s.name}</strong><span className="muted">Learner</span></div>) : <div className="empty"><div className="empty-icon"><Users/></div><h3>No students yet</h3><p>Add learners to this local classroom.</p></div>}</div></>}</section></div>{selected && <section className="card assignment-card"><div className="card-head"><div><h2>Assign learning</h2><p>Students can access assigned content without internet.</p></div><CheckCircle2 size={20}/></div><div className="assign-form"><select value={contentId} onChange={e=>setContentId(e.target.value)}><option value="">Choose lesson or quiz</option>{state.lessons.map(l=><option value={l.id} key={l.id}>Lesson · {l.title}</option>)}{state.quizzes.map(q=><option value={q.id} key={q.id}>Quiz · {q.title}</option>)}</select><button className="btn btn-primary" onClick={assign}><BookOpen size={17}/> Assign to class</button></div>{data.assignments.filter(a=>a.classId===selected.id).map(a=><div className="assignment-row" key={a.id}><span>{a.contentType}</span><strong>{state.lessons.find(x=>x.id===a.contentId)?.title || state.quizzes.find(x=>x.id===a.contentId)?.title || a.contentId}</strong><span className="badge badge-success">Assigned</span></div>)}</section>}</div>;
}
